"""Connections: curated threads between works that sit apart on the map (W['routes']).

A portal says a work belongs on a second island too (Butch Cassidy is a western). A connection says works
in different places belong to one story: who inspired whom, one creator or composer across genres, one
author's world in several media, or one idea (a philosophy, a question, a theme) at the heart of each. Each is traced across the map through its stops, in release order.
Keep to what is documented (said by the makers, credited, or widely reported), and only works on the map
(planned ones included: a thread can point at what is still to read or watch).
usage: python3 routes.py SITE_DIR
"""
import json, re, sys
from pathlib import Path

SITE = Path(sys.argv[1])
html = (SITE / 'index.html').read_text()
m = re.search(r'(<script type="application/json" id="world">)(.*?)(</script>)', html, re.S)
W = json.loads(m.group(2))
items = {i['id']: i for i in W['items']}

# (id, name, name in Spanish, blurb, blurb in Spanish, stop ids in order)
ROUTES = [
    # --- the three bests ---
    ('big3seinen', 'The Big Three of seinen', 'Los tres grandes del seinen',
     "The trio seinen readers most often name as the peak of the form: Miura's Berserk, Inoue's Vagabond and Urasawa's Monster.",
     'El trío que los lectores de seinen señalan como la cumbre del género: Berserk de Miura, Vagabond de Inoue y Monster de Urasawa.',
     ['m5h', 'm5v', 'm63']),
    ('big3shonen', 'The Big Three of Shōnen Jump', 'Los tres grandes de la Shōnen Jump',
     'The three series that carried Weekly Shōnen Jump through the 2000s.',
     'Las tres series que sostuvieron la Weekly Shōnen Jump durante los 2000.',
     ['m5i', 'm93', 'm68']),
    # --- inspiration ---
    ('kurosawa', "Kurosawa's descendants", 'Los herederos de Kurosawa',
     "George Lucas has said The Hidden Fortress shaped Star Wars, told through two squabbling peasants. Sergio Leone's A Fistful of Dollars is an unauthorised remake of Yojimbo.",
     'George Lucas ha dicho que La fortaleza escondida dio forma a Star Wars, contada por dos campesinos que se pelean. Por un puñado de dólares de Sergio Leone es un remake no autorizado de Yojimbo.',
     ['fkk', 'fzi', 'fk6', 'fjq']),
    ('berserksouls', "Berserk's long shadow", 'La larga sombra de Berserk',
     "Hidetaka Miyazaki has cited Kentaro Miura's Berserk as a key influence on FromSoftware's dark fantasy.",
     'Hidetaka Miyazaki ha citado el Berserk de Kentaro Miura como una influencia clave en la fantasía oscura de FromSoftware.',
     ['m5h', 'g179', 'g16f', 'g14z', 'g14c', 'g11t']),
    ('lovecraft', "Lovecraft's heirs", 'Los herederos de Lovecraft',
     "Cosmic horror after Lovecraft: John Carpenter's The Thing, Junji Ito (who cites Lovecraft among his influences) and FromSoftware's Bloodborne.",
     'El horror cósmico después de Lovecraft: La cosa de John Carpenter, Junji Ito (que cita a Lovecraft entre sus influencias) y Bloodborne de FromSoftware.',
     ['be9', 'fym', 'm5r', 'g14z']),
    ('killbill', "Kill Bill's ingredients", 'Los ingredientes de Kill Bill',
     "Tarantino built the Bride's revenge on Lady Snowblood and cast Gordon Liu, star of The 36th Chamber of Shaolin, in both volumes.",
     'Tarantino construyó la venganza de la Novia sobre Lady Snowblood y eligió a Gordon Liu, estrella de La cámara 36 de Shaolin, en los dos volúmenes.',
     ['f101', 'fzf', 'fu1', 'ftr']),
    ('doomroots', 'What Doom was made of', 'De qué está hecho Doom',
     "id Software has described Doom as Aliens meets Evil Dead II: marines, a chainsaw and a base overrun by demons.",
     'id Software ha descrito Doom como Aliens con Posesión infernal II: marines, una motosierra y una base invadida por demonios.',
     ['fy0', 'fxw', 'g19y', 'g19v']),
    ('twinpeaks', "Twin Peaks' long shadow", 'La larga sombra de Twin Peaks',
     "David Lynch's small-town dread is a named influence on Silent Hill and on Remedy's Alan Wake games.",
     'El inquietante pueblo de David Lynch es una influencia reconocida de Silent Hill y de los Alan Wake de Remedy.',
     ['t1dn', 'g19a', 'g191', 'g11h']),
    ('strangerthings', "Stranger Things' ingredients", 'Los ingredientes de Stranger Things',
     "The Duffer brothers built Stranger Things out of Spielberg's suburbs, Stephen King's kids on bikes and John Carpenter's The Thing, whose poster hangs in Mike's basement.",
     'Los hermanos Duffer construyeron Stranger Things con los barrios de Spielberg, los chavales en bici de Stephen King y La cosa de John Carpenter, cuyo póster cuelga en el sótano de Mike.',
     ['fyo', 'fym', 'fxz', 't1c4']),
    ('madmax', 'From Mad Max to Fallout', 'De Mad Max a Fallout',
     "Fallout's wasteland owes a lot to The Road Warrior: its dog Dogmeat and its leather-jacketed wanderer are nods to Mad Max 2.",
     'El yermo de Fallout le debe mucho a Mad Max 2: el perro Dogmeat y su vagabundo de chaqueta de cuero son guiños a la película.',
     ['fz8', 'fyr', 'g166', 'fo6', 't1bz']),
    ('cyberpunk', "Cyberpunk's family tree", 'El árbol del cyberpunk',
     'Blade Runner set the look of the neon future; Akira and Ghost in the Shell carried it into manga and anime, and the Wachowskis showed Ghost in the Shell to their producer to explain The Matrix. Night City carries the line on.',
     'Blade Runner fijó el aspecto del futuro de neón; Akira y Ghost in the Shell lo llevaron al manga y al anime, y las Wachowski enseñaron Ghost in the Shell a su productor para explicarle Matrix. Night City sigue la línea.',
     ['fyn', 'm5y', 'a1s', 'fvh', 'fn4', 'g124', 'a2d']),
    ('dracula', "Dracula's descendants", 'Los descendientes de Drácula',
     "Bram Stoker's count is the enemy the Belmonts face in Castlevania from the first game on; Coppola went back to the novel in 1992.",
     'El conde de Bram Stoker es el enemigo de los Belmont en Castlevania desde el primer juego; Coppola volvió a la novela en 1992.',
     ['bdd', 'g1ac', 'fwz']),
    ('cuphead', "Cuphead's 1930s", 'Los años treinta de Cuphead',
     "Studio MDHR drew Cuphead by hand in the style of the Fleischer brothers' 1930s cartoons.",
     'Studio MDHR dibujó Cuphead a mano al estilo de los dibujos de los hermanos Fleischer de los años treinta.',
     ['flx', 'g13l']),
    ('shakespeare', 'Shakespeare, retold', 'Shakespeare, contado de nuevo',
     "Kurosawa moved Macbeth and King Lear to feudal Japan, Disney's The Lion King takes its plot from Hamlet, The Northman goes back to Amleth, the Norse legend Hamlet came from, and Hamnet imagines the grief behind it.",
     'Kurosawa llevó Macbeth y El rey Lear al Japón feudal, El rey león de Disney toma su trama de Hamlet, El hombre del norte vuelve a Amleth, la leyenda nórdica de la que salió Hamlet, y Hamnet imagina el duelo que hay detrás.',
     ['fkv', 'fy7', 'fwi', 'fj2', 'fi1']),
    ('dune', "Dune and Star Wars", 'Dune y Star Wars',
     "Frank Herbert's desert planet, its spice and its chosen son are often named among Star Wars' sources; Villeneuve's films go back to the novel.",
     'El planeta desierto de Frank Herbert, su especia y su elegido suelen citarse entre las fuentes de Star Wars; las películas de Villeneuve vuelven a la novela.',
     ['bap', 'fzi', 'fja', 'fic']),
    ('tolkien', "Tolkien's road", 'El camino de Tolkien',
     'Middle-earth, and The Wheel of Time, whose opening Robert Jordan modelled on The Fellowship of the Ring on purpose.',
     'La Tierra Media y La Rueda del Tiempo, cuyo comienzo Robert Jordan escribió a propósito como eco de La Comunidad del Anillo.',
     ['bhb', 'bd7', 'bdl']),
    ('christie', "Agatha Christie's islands", 'Las islas de Agatha Christie',
     "Christie's island of ten guests, Billy Wilder's film of her play, and Umineko, which sets its own island mystery against And Then There Were None by name.",
     'La isla de los diez invitados de Christie, la película de Billy Wilder sobre su obra de teatro y Umineko, que enfrenta su propio misterio en una isla a Diez negritos por su nombre.',
     ['bbn', 'fkm', 'm7g']),
    ('alice', 'Down the rabbit hole', 'Por la madriguera del conejo',
     "Lewis Carroll's Wonderland, Disney's two trips there, and The Matrix, which sends Neo after the white rabbit and down the rabbit hole.",
     'El País de las Maravillas de Lewis Carroll, los dos viajes de Disney allí y Matrix, que manda a Neo detrás del conejo blanco y madriguera abajo.',
     ['bez', 'flc', 'fvh', 'fqu']),
    ('kon', "Perfect Blue's echo", 'El eco de Perfect Blue',
     "Darren Aronofsky bought the rights to Satoshi Kon's Perfect Blue and restaged its bathtub shot in Requiem for a Dream.",
     'Darren Aronofsky compró los derechos de Perfect Blue de Satoshi Kon y recreó su plano de la bañera en Réquiem por un sueño.',
     ['a1t', 'fv3']),
    # --- one hand across the map ---
    ('toriyama', "Toriyama's children", 'Los hijos de Toriyama',
     'Akira Toriyama drew Dragon Ball and the characters of Dragon Quest and Chrono Trigger; Eiichiro Oda and Masashi Kishimoto have both named Dragon Ball as why they draw manga.',
     'Akira Toriyama dibujó Dragon Ball y los personajes de Dragon Quest y Chrono Trigger; Eiichiro Oda y Masashi Kishimoto han dicho que dibujan manga por Dragon Ball.',
     ['m6j', 'g17f', 'g19r', 'm5i', 'm93']),
    ('martin', "George R. R. Martin's worlds", 'Los mundos de George R. R. Martin',
     "Westeros on the page and on HBO, and the Lands Between, whose ancient history Martin wrote for FromSoftware's Elden Ring.",
     'Poniente en papel y en HBO, y las Tierras Intermedias, cuya historia antigua escribió Martin para Elden Ring de FromSoftware.',
     ['bed', 't1dq', 'g11t', 't1cg', 't1bv']),
    ('naughtydog', 'Naughty Dog', 'Naughty Dog',
     "Naughty Dog's run from Crash Bandicoot and Jak and Daxter to Uncharted and The Last of Us, which its co-creator Neil Druckmann also brought to HBO.",
     'La trayectoria de Naughty Dog, de Crash Bandicoot y Jak and Daxter a Uncharted y The Last of Us, que su cocreador Neil Druckmann también llevó a HBO.',
     ['g19m', 'g18y', 'g17l', 'g15o', 'g14b', 't1cm']),
    ('kamiya', 'Born from Resident Evil 4', 'Nacido de Resident Evil 4',
     "Hideki Kamiya directed Resident Evil 2; his prototype for Resident Evil 4 became Devil May Cry, and Capcom took Resident Evil 4 another way.",
     'Hideki Kamiya dirigió Resident Evil 2; su prototipo de Resident Evil 4 se convirtió en Devil May Cry, y Capcom llevó Resident Evil 4 por otro camino.',
     ['g19h', 'g18f', 'g185', 'g130']),
    ('insomniac', 'Insomniac Games', 'Insomniac Games',
     "Insomniac's games, from Ratchet & Clank's gadgets to Marvel's Spider-Man.",
     'Los juegos de Insomniac, de los artilugios de Ratchet & Clank a Marvel\'s Spider-Man.',
     ['g18m', 'g139']),
    ('coens', 'The Coen brothers', 'Los hermanos Coen',
     "Joel and Ethan Coen's crime stories, from Fargo to their Cormac McCarthy adaptation, and the Fargo series made with them as executive producers.",
     'Las historias criminales de Joel y Ethan Coen, de Fargo a su adaptación de Cormac McCarthy, y la serie Fargo, con ellos como productores ejecutivos.',
     ['fvw', 'fvn', 'fsb', 't1d8']),
    ('ridley', "Ridley Scott's worlds", 'Los mundos de Ridley Scott',
     "Ridley Scott's worlds: the Nostromo, Los Angeles 2019, Rome, Sherwood and Mars.",
     'Los mundos de Ridley Scott: la Nostromo, Los Ángeles 2019, Roma, Sherwood y Marte.',
     ['fz6', 'fyn', 'fv4', 'fqr', 'fnz']),
    ('watanabe', "Shinichirō Watanabe's anime", 'El anime de Shinichirō Watanabe',
     'Jazz among bounty hunters in space, then hip-hop in Edo.',
     'Jazz entre cazarrecompensas en el espacio, y luego hip-hop en Edo.',
     ['a1g', 'a4j', 'a1h']),
    ('urobuchi', 'Written by Gen Urobuchi', 'Escrito por Gen Urobuchi',
     'Gen Urobuchi wrote both Madoka Magica and the first Psycho-Pass.',
     'Gen Urobuchi escribió Madoka Magica y la primera temporada de Psycho-Pass.',
     ['a4b', 'a3p', 'a4f']),
    ('cosmere', 'The Cosmere', 'El Cosmere',
     "Brandon Sanderson's novels share one universe, tied together by worldhoppers like Hoid.",
     'Las novelas de Brandon Sanderson comparten un universo, unido por viajeros entre mundos como Hoid.',
     ['bbj', 'bf2', 'bh9', 'be8', 'bbi', 'bg3', 'be5', 'bf4', 'be6', 'bf3', 'bb8']),
    ('shooters', 'From Doom to Ultrakill', 'De Doom a Ultrakill',
     "The first-person shooters on the map, in release order: id's Doom, Valve's story shooters, Halo on console, and the retro revival.",
     'Los shooters en primera persona del mapa, en orden: el Doom de id, los shooters narrativos de Valve, Halo en consola y el revival retro.',
     ['g19y', 'g19v', 'g19d', 'g18z', 'g18i', 'g17u', 'g14a', 'g135', 'g12b']),
    ('square', "Square's golden age", 'La edad de oro de Square',
     "Square's run of role-playing games from 1994 to 2000, several of them scored by Nobuo Uematsu.",
     'Los juegos de rol de Square de 1994 a 2000, varios con música de Nobuo Uematsu.',
     ['g19w', 'm1g1', 'g19r', 'g19j', 'm1g2', 'g19g', 'g194']),
    ('hbo', "HBO's golden age", 'La edad de oro de HBO',
     "HBO's run of prestige drama, from The Sopranos to Chernobyl.",
     'Los dramas de prestigio de HBO, de Los Soprano a Chernobyl.',
     ['t1bs', 't1dj', 't1do', 't1dq', 't1cs']),
    # --- ideas and themes: works whose main idea is the same philosophy or question ---
    ('nietzsche', "Nietzsche's shadow", 'La sombra de Nietzsche',
     "Nietzsche's own Beyond Good and Evil; Hesse's Steppenwolf, steeped in him; 2001: A Space Odyssey, opening on Strauss's Also sprach Zarathustra and ending on a new kind of being; and Xenogears, built on Nietzsche, Freud and Jung.",
     'Más allá del bien y del mal del propio Nietzsche; El lobo estepario de Hesse, impregnado de él; 2001: Una odisea del espacio, que se abre con el Así habló Zaratustra de Strauss y termina en un nuevo tipo de ser; y Xenogears, construido sobre Nietzsche, Freud y Jung.',
     ['bdx', 'bb4', 'f10m', 'g19g']),
    ('existence', 'Existence before meaning', 'La existencia antes que el sentido',
     "Existentialism's question, what a life means when nothing hands it a meaning: Dostoevsky's student who kills to prove a theory, Travis Bickle (Schrader has named Sartre's Nausea among his sources), Evangelion's episode named after Kierkegaard's The Sickness Unto Death, Tyler Durden's nihilism, and NieR: Automata, whose machines take the names of Sartre, Pascal and Kierkegaard.",
     'La pregunta del existencialismo, qué significa una vida cuando nada le da sentido: el estudiante de Dostoievski que mata para probar una teoría, Travis Bickle (Schrader ha citado La náusea de Sartre entre sus fuentes), el episodio de Evangelion titulado como La enfermedad mortal de Kierkegaard, el nihilismo de Tyler Durden y NieR: Automata, cuyas máquinas se llaman Sartre, Pascal y Kierkegaard.',
     ['bfl', 'fzm', 'a10', 'fvb', 'g13v']),
    ('faith', 'Faith on trial', 'La fe a prueba',
     "Faith under trial: Dreyer's Joan before her judges, Bergman's knight playing chess with Death and demanding proof of God, Tarkovsky's icon painter falling silent, and Blasphemous's penitent in a land of Spanish Catholic guilt.",
     'La fe a prueba: la Juana de Dreyer ante sus jueces, el caballero de Bergman jugando al ajedrez con la Muerte y exigiendo pruebas de Dios, el pintor de iconos de Tarkovski que enmudece y el Penitente de Blasphemous en una tierra de culpa católica española.',
     ['fm0', 'fku', 'f10r', 'g12t']),
    ('mortality', 'Living with death', 'Vivir con la muerte',
     "What a life is worth once its end is in sight: a dying clerk who finally does one thing that matters, an old professor driving back through his life, an elf learning too late what a short human life was worth, and two stories of grief.",
     'Lo que vale una vida cuando se ve su final: un funcionario moribundo que por fin hace algo que importa, un viejo profesor que recorre su vida en coche, una elfa que aprende tarde lo que valía una vida humana corta y dos historias de duelo.',
     ['fl9', 'fkq', 'a38', 'a4g', 'fi1']),
    ('mind', 'What makes a mind', 'Qué hace a una mente',
     "Philosophy of mind: replicants with borrowed memories, Ghost in the Shell (named after Arthur Koestler's The Ghost in the Machine), Lain's self dissolving into the Wired, and SOMA's scanned minds waking in bodies that aren't theirs.",
     'Filosofía de la mente: replicantes con recuerdos prestados, Ghost in the Shell (que toma su nombre de El fantasma en la máquina de Arthur Koestler), el yo de Lain disolviéndose en la Wired y las mentes escaneadas de SOMA despertando en cuerpos que no son suyos.',
     ['fyn', 'a1s', 'a1z', 'g14s', 'fn4']),
    ('real', 'Is any of this real?', '¿Algo de esto es real?',
     "Lives inside a made-up world: a town that is a television set, a world that is code (The Matrix puts Baudrillard's Simulacra and Simulation on screen), and dreams inside dreams.",
     'Vidas dentro de un mundo inventado: un pueblo que es un plató de televisión, un mundo que es código (Matrix muestra en pantalla Cultura y simulacro de Baudrillard) y sueños dentro de sueños.',
     ['fvk', 'fvh', 'fqk']),
    ('fate', 'Knowing what is coming', 'Saber lo que viene',
     "Fate and free will: Paul Atreides trapped by his own prescience, Okabe fighting a future the worldlines won't let go of, Louise choosing a life whose end she already knows, and a solar system that ends every 22 minutes.",
     'Destino y libre albedrío: Paul Atreides atrapado por su propia presciencia, Okabe luchando contra un futuro que las líneas temporales no sueltan, Louise eligiendo una vida cuyo final ya conoce y un sistema solar que se acaba cada 22 minutos.',
     ['bap', 'aa', 'fnk', 'g12w']),
    ('state', 'The state against the self', 'El Estado contra el individuo',
     "Free will against the state: Kubrick's Alex reconditioned into goodness, Alan Moore's anarchist V, Panem's televised games, and Psycho-Pass's Sibyl System, a panopticon argued over by characters who quote Orwell, Pascal and Philip K. Dick.",
     'El libre albedrío contra el Estado: el Alex de Kubrick reacondicionado para ser bueno, el V anarquista de Alan Moore, los juegos televisados de Panem y el Sistema Sibyl de Psycho-Pass, un panóptico debatido por personajes que citan a Orwell, Pascal y Philip K. Dick.',
     ['f10a', 'chh', 'fpp', 'a3p']),
    ('ideologies', 'Ideologies at work', 'Ideologías en juego',
     "Political philosophy as the story: Legend of the Galactic Heroes weighing an enlightened autocrat against a failing democracy, BioShock's Rapture as Ayn Rand's Objectivism taken to its end, and Disco Elysium, where communism, fascism, ultraliberalism and moralism are things your detective can become.",
     'La filosofía política como historia: Legend of the Galactic Heroes enfrentando a un autócrata ilustrado con una democracia en declive, la Rapture de BioShock como el objetivismo de Ayn Rand llevado al extremo y Disco Elysium, donde comunismo, fascismo, ultraliberalismo y moralismo son cosas en las que tu detective puede convertirse.',
     ['a18', 'g17u', 'g120']),
    ('hatred', 'Ending the cycle of hatred', 'Romper el ciclo del odio',
     "How a cycle of hatred ends: One Piece's Fish-Man Island and the hatred handed down there, Naruto facing Pain, Vinland Saga's warrior who decides he has no enemies, Attack on Titan's war without innocents, and Undertale, which lets you finish without killing anyone.",
     'Cómo se rompe un ciclo de odio: la Isla Gyojin de One Piece y el odio que se hereda allí, Naruto frente a Pain, el guerrero de Vinland Saga que decide no tener enemigos, la guerra sin inocentes de Attack on Titan y Undertale, que deja terminar sin matar a nadie.',
     ['m5i', 'm93', 'm5t', 'm5l', 'g14t']),
    ('fall', 'How a good man goes bad', 'Cómo se corrompe un buen hombre',
     "Vince Gilligan pitched Breaking Bad as turning Mr. Chips into Scarface; the same descent runs through Macbeth in Kurosawa's Throne of Blood, Michael Corleone, and Jimmy McGill becoming Saul.",
     'Vince Gilligan presentó Breaking Bad como convertir a Mr. Chips en Scarface; la misma caída recorre a Macbeth en Trono de sangre de Kurosawa, a Michael Corleone y a Jimmy McGill convirtiéndose en Saul.',
     ['fkv', 'f109', 't1dr', 't1da']),
    ('bushido', 'The way of the sword', 'El camino de la espada',
     "Musashi's own book of strategy and Zen, Yoshikawa's novel of his life, Inoue's Vagabond drawn from it, and two games about what a warrior's code costs: Sekiro and Ghost of Tsushima.",
     'El libro de estrategia y zen del propio Musashi, la novela de Yoshikawa sobre su vida, el Vagabond de Inoue basado en ella y dos juegos sobre lo que cuesta el código de un guerrero: Sekiro y Ghost of Tsushima.',
     ['bgp', 'bf5', 'm5v', 'g12z', 'g12f']),
    ('balance', 'Balance and the Way', 'El equilibrio y el Camino',
     "Taoist and Buddhist ideas told for everyone: Avatar's four nations and Iroh's patience, and Master Oogway's 'there are no accidents'.",
     'Ideas taoístas y budistas contadas para todos: las cuatro naciones de Avatar y la paciencia de Iroh, y el "no hay accidentes" del maestro Oogway.',
     ['t1dt', 'frr']),
    ('nature', 'Living with nature', 'Vivir con la naturaleza',
     "People living with nature rather than against it: Kurosawa's Siberian hunter, Miyazaki's toxic jungle and forest gods, and Cameron's Pandora.",
     'Vivir con la naturaleza y no contra ella: el cazador siberiano de Kurosawa, la jungla tóxica y los dioses del bosque de Miyazaki, y la Pandora de Cameron.',
     ['fzq', 'a2g', 'a14', 'fqw']),
    ('pessimism', 'Cosmic pessimism', 'Pesimismo cósmico',
     "The universe doesn't care: Lovecraft's old gods, and True Detective's Rust Cohle, whose monologues draw on the pessimist writer Thomas Ligotti, as its creator has acknowledged.",
     'Al universo le da igual: los dioses antiguos de Lovecraft y el Rust Cohle de True Detective, cuyos monólogos beben del escritor pesimista Thomas Ligotti, como ha reconocido su creador.',
     ['be9', 't1db']),
    ('freedom', 'The freest man', 'El hombre más libre',
     "Freedom as the thing worth everything: Andy Dufresne's tunnel, Luffy's dream of being the freest man on the sea, Eren's world beyond the walls, and the last days of Dutch's gang as the frontier closes.",
     'La libertad como lo que lo vale todo: el túnel de Andy Dufresne, el sueño de Luffy de ser el hombre más libre del mar, el mundo de Eren más allá de los muros y los últimos días de la banda de Dutch mientras se cierra la frontera.',
     ['fwf', 'm5i', 'm5l', 'g137']),
    ('family', 'Found family', 'La familia elegida',
     "Families people choose: the Straw Hats, the Bebop's crew of strays, 'ohana means family', Dom Toretto's table, the Guardians, and the Forgers, a family faked for a mission that turns real.",
     'Familias que se eligen: los Sombrero de Paja, la tripulación de descarriados del Bebop, "ohana significa familia", la mesa de Dom Toretto, los Guardianes y los Forger, una familia fingida para una misión que se vuelve de verdad.',
     ['m5i', 'a1g', 'fuf', 'fq8', 'fog', 'a20']),
    ('inherited', 'What is passed on', 'Lo que se hereda',
     "Inherited will: Mufasa in the stars telling Simba to remember who he is, One Piece's 'inherited will, the flow of the age, and people's dreams', Naruto's Will of Fire, and Kamina's drill in Simon's hands.",
     'La voluntad heredada: Mufasa en las estrellas diciéndole a Simba que recuerde quién es, la "voluntad heredada, el curso de los tiempos y los sueños de la gente" de One Piece, la Voluntad del Fuego de Naruto y el taladro de Kamina en manos de Simon.',
     ['fwi', 'm5i', 'm93', 'a45']),
    ('revenge', 'The cost of revenge', 'El precio de la venganza',
     "Revenge and what it costs: Dantès's patient plan, Lady Snowblood born for vengeance, Guts's war on Griffith, Maximus, Oh Dae-su's fifteen years, Thorfinn learning to put it down, Glass crawling back from the dead, and Ellie's Seattle.",
     'La venganza y lo que cuesta: el plan paciente de Dantès, Lady Snowblood nacida para vengarse, la guerra de Guts contra Griffith, Máximo, los quince años de Oh Dae-su, Thorfinn aprendiendo a soltarla, Glass arrastrándose de vuelta de la muerte y la Seattle de Ellie.',
     ['bbq', 'f101', 'm5h', 'fv4', 'ftz', 'm5t', 'fnu', 'g12h']),
    ('american', 'The American dream, gone wrong', 'El sueño americano, torcido',
     "Fortunes made and souls sold: Kane's Xanadu, the Corleones, Tony Montana's world, Henry Hill, Daniel Plainview's oil, Walter White's empire and Jordan Belfort.",
     'Fortunas hechas y almas vendidas: el Xanadú de Kane, los Corleone, el mundo de Tony Montana, Henry Hill, el petróleo de Daniel Plainview, el imperio de Walter White y Jordan Belfort.',
     ['fls', 'f109', 'fyi', 'fxg', 'fs2', 't1dr', 'foq']),
    ('memory', 'Memory and who we are', 'La memoria y quiénes somos',
     "Memory as identity: a man who can't make new ones, lovers who erase each other, a mind run by its feelings, two strangers forgetting each other's names, and the final death of being forgotten.",
     'La memoria como identidad: un hombre que no puede crear recuerdos nuevos, amantes que se borran el uno al otro, una mente gobernada por sus emociones, dos desconocidos que olvidan el nombre del otro y la muerte definitiva de ser olvidado.',
     ['fuw', 'ftu', 'fo5', 'a13', 'fn3']),
    ('greatness', 'The price of greatness', 'El precio de ser grande',
     "What it takes: Joe burning down to white ash, Rocky going the distance, Hanamichi's back for one last game, and Fletcher's 'not quite my tempo'.",
     'Lo que cuesta: Joe consumiéndose hasta quedar en ceniza blanca, Rocky aguantando hasta el final, la espalda de Hanamichi en un último partido y el "no es mi tempo" de Fletcher.',
     ['m69', 'fzj', 'm66', 'fop']),
    # --- composers ---
    ('morricone', "Ennio Morricone's scores", 'Las bandas sonoras de Ennio Morricone',
     "Every Sergio Leone film on the map, and Morricone's scores beyond the West: The Battle of Algiers, The Thing, The Untouchables, Cinema Paradiso, and the Oscar at last for The Hateful Eight.",
     'Todas las películas de Sergio Leone del mapa y las bandas sonoras de Morricone más allá del Oeste: La batalla de Argel, La cosa, Los intocables, Cinema Paradiso y, por fin, el Óscar por Los odiosos ocho.',
     ['fjq', 'fjj', 'f10q', 'm1l4', 'fjh', 'f10h', 'fym', 'fyd', 'fxu', 'fxn', 'fnw']),
    ('zimmer', "Hans Zimmer's scores", 'Las bandas sonoras de Hans Zimmer',
     "Hans Zimmer's scores, alone or with collaborators, from Rain Man to Nolan's films and Villeneuve's Dune; The Lion King and Dune both won him the Oscar.",
     'Las bandas sonoras de Hans Zimmer, solo o con colaboradores, de Rain Man a las películas de Nolan y el Dune de Villeneuve; El rey león y Dune le dieron el Óscar.',
     ['fxm', 'fwi', 'fv4', 'fty', 'ftb', 'fsm', 'frl', 'fqk', 'fod', 'm1gm', 'fn8', 'fn4', 'fja', 'fic', 'm1gn']),
    ('williams', "John Williams' scores", 'Las bandas sonoras de John Williams',
     'John Williams scored nearly every Spielberg film and the Star Wars saga; Jaws, Star Wars, E.T. and Schindler\'s List all won him the Oscar.',
     'John Williams puso música a casi todas las películas de Spielberg y a la saga Star Wars; Tiburón, Star Wars, E.T. y La lista de Schindler le dieron el Óscar.',
     ['fzr', 'fzi', 'm1gd', 'fz1', 'fyu', 'fyo', 'fxe', 'fwu', 'fwp', 'fvi', 'fum', 'fiw']),
]

# More connections, each with its kind first: (kind, id, name, name in Spanish, blurb, blurb in Spanish, stops).
MORE = [
 # ---------------- ideas and themes ----------------
 ('idea', 'growingup', 'Growing up', 'Hacerse mayor',
  "Coming of age: four boys walking to see a body, a young witch on her own in a new town, South Central, 1960s Taipei, a girl deciding to write, Riley's feelings, and a boy who wants to make films.",
  'Hacerse mayor: cuatro chavales caminando para ver un cadáver, una joven bruja sola en una ciudad nueva, South Central, el Taipéi de los sesenta, una chica que decide escribir, las emociones de Riley y un chico que quiere hacer películas.',
  ['fxz', 'a36', 'fxa', 'fx8', 'a34', 'fo5', 'fiw']),
 ('idea', 'making', 'Making art', 'Hacer arte',
  "The work and what it costs the maker: a dancer who can't stop, Fellini's blocked director, Tarkovsky's icon painter, Bob Fosse's own life, Salieri's envy, a student finding painting, two girls drawing manga, and Spielberg's first films.",
  'La obra y lo que le cuesta a quien la hace: una bailarina que no puede parar, el director bloqueado de Fellini, el pintor de iconos de Tarkovski, la propia vida de Bob Fosse, la envidia de Salieri, un estudiante que descubre la pintura, dos chicas que dibujan manga y las primeras películas de Spielberg.',
  ['fli', 'fjz', 'f10r', 'fz3', 'fyb', 'm9c', 'm6v', 'fiw']),
 ('idea', 'musicians', 'A life in music', 'Una vida en la música',
  "Musicians and what music asks of them: Mozart and Salieri, Nana's punk band, a pianist who can't hear his own playing, a drummer's blood, a jazz pianist in Los Angeles, a boy who wants to play in the Land of the Dead, a teacher who finally gets the gig, the Beatles writing Let It Be, and Elvis.",
  'Músicos y lo que la música les pide: Mozart y Salieri, la banda punk de Nana, un pianista que no oye su propia música, la sangre de un batería, un pianista de jazz en Los Ángeles, un niño que quiere tocar en la Tierra de los Muertos, un profesor que por fin consigue el bolo, los Beatles componiendo Let It Be y Elvis.',
  ['fyb', 'm7f', 'a30', 'fop', 'fnl', 'fn3', 'fm4', 't1bu', 'fj0']),
 ('idea', 'loneliness', 'Alone in the city', 'Solo en la ciudad',
  "Loneliness among millions: Travis Bickle's night shifts, Wong Kar-wai's Hong Kong strangers, Arthur Fleck's stairs, and Hirayama's quiet routine in Tokyo.",
  'La soledad entre millones: los turnos de noche de Travis Bickle, los desconocidos del Hong Kong de Wong Kar-wai, las escaleras de Arthur Fleck y la rutina tranquila de Hirayama en Tokio.',
  ['fzm', 'fwg', 'fw4', 'fmf', 'fim']),
 ('idea', 'class', 'Upstairs, downstairs', 'Los de arriba y los de abajo',
  "Class: Metropolis's workers below the city, Chaplin's tramp in the machine, a stolen bicycle in postwar Rome, the rich on Elysium's orbit, the Roys, and the Kims in the semi-basement.",
  'La clase social: los obreros bajo la ciudad de Metrópolis, el vagabundo de Chaplin dentro de la máquina, una bicicleta robada en la Roma de posguerra, los ricos en la órbita de Elysium, los Roy y los Kim en el semisótano.',
  ['fm1', 'fly', 'flj', 'foy', 't1cc', 'fmm']),
 ('idea', 'parents', 'Parents and children', 'Padres e hijos',
  "Parents and children: a ronin pushing his son's cart, Travis walking out of the desert to find his family, Marlin crossing the ocean, Joel and Ellie, Cooper's messages from beyond time, and Kratos teaching Atreus.",
  'Padres e hijos: un ronin empujando el carrito de su hijo, Travis saliendo del desierto para buscar a su familia, Marlin cruzando el océano, Joel y Ellie, los mensajes de Cooper desde más allá del tiempo y Kratos enseñando a Atreus.',
  ['m8x', 'fye', 'fu7', 'g15o', 'fod', 'g13e']),
 ('idea', 'mothers', 'Mothers', 'Madres',
  "Mothers, loved, feared and remembered: Norman Bates's, Tarkovsky's in Mirror, Jeanne Dielman's routine, Bergman's pianist and her daughter, Hereditary's grief, and Evelyn across every universe.",
  'Madres queridas, temidas y recordadas: la de Norman Bates, la de Tarkovski en El espejo, la rutina de Jeanne Dielman, la pianista de Bergman y su hija, el duelo de Hereditary y Evelyn a través de todos los universos.',
  ['fkb', 'fzu', 'fzs', 'fzb', 'fn0', 'fj3']),
 ('idea', 'warchildren', 'War through a child\'s eyes', 'La guerra vista por un niño',
  "War seen by children: a Belarusian boy at Come and See, Seita and Setsuko, a father turning a camp into a game, and Ofelia escaping into a labyrinth.",
  'La guerra vista por niños: un chico bielorruso en Ven y mira, Seita y Setsuko, un padre que convierte un campo en un juego y Ofelia huyendo a un laberinto.',
  ['fy4', 'a16', 'fvo', 'fsn']),
 ('idea', 'holocaust', 'Remembering the Holocaust', 'Recordar el Holocausto',
  "The Holocaust remembered: Spiegelman drawing his father's story, Schindler's list, Guido's game, and Szpilman hiding in Warsaw.",
  'El Holocausto recordado: Spiegelman dibujando la historia de su padre, la lista de Schindler, el juego de Guido y Szpilman escondido en Varsovia.',
  ['bfa', 'fwp', 'fvo', 'fuh']),
 ('idea', 'atom', 'The atomic age', 'La era atómica',
  "Living under the bomb: Dr. Strangelove's doomsday machine, Neo-Tokyo after the war, the Mojave after the bombs, Chernobyl's reactor, Oppenheimer himself, a postwar Japan meeting Godzilla, and the Vaults opening again.",
  'Vivir bajo la bomba: la máquina del fin del mundo de Dr. Strangelove, Neo-Tokio después de la guerra, el Mojave después de las bombas, el reactor de Chernóbil, el propio Oppenheimer, un Japón de posguerra frente a Godzilla y los Refugios abriéndose otra vez.',
  ['fjs', 'm5y', 'g166', 't1cs', 'fii', 'fif', 't1bz']),
 ('influence', 'zone', 'The Zone', 'La Zona',
  "The Strugatskys' Roadside Picnic became Tarkovsky's Stalker; GSC's S.T.A.L.K.E.R. games put that Zone in the real Chernobyl exclusion zone, whose disaster HBO's Chernobyl retells.",
  'Picnic extraterrestre de los Strugatski se convirtió en el Stalker de Tarkovski; los juegos S.T.A.L.K.E.R. de GSC llevaron esa Zona a la zona de exclusión real de Chernóbil, cuyo desastre cuenta la Chernobyl de HBO.',
  ['ba4', 'fz5', 't1cs', 'g118']),
 ('idea', 'robots', 'Machines that feel', 'Máquinas que sienten',
  "Machines and their hearts: HAL pleading as he is switched off, a robot who wants to be human, the Iron Giant, Pluto's robots learning to hate, WALL·E, and Roz on her island.",
  'Las máquinas y su corazón: HAL suplicando mientras lo apagan, un robot que quiere ser humano, el Gigante de Hierro, los robots de Pluto aprendiendo a odiar, WALL·E y Roz en su isla.',
  ['f10m', 'fv7', 'fve', 'm60', 'frn', 'fi5']),
 ('idea', 'time', 'Playing with time', 'Jugar con el tiempo',
  "Time travel and loops: a DeLorean at 88 mph, a party that crosses the ages, three days before the moon falls, a jet engine falling through time, D-mail, Winden's caves, a 22-minute solar system, and a time that runs backwards.",
  'Viajes en el tiempo y bucles: un DeLorean a 88 millas por hora, un grupo que cruza las eras, tres días antes de que caiga la luna, un motor de avión cayendo a través del tiempo, los D-mail, las cuevas de Winden, un sistema solar de 22 minutos y un tiempo que corre hacia atrás.',
  ['fy5', 'g19r', 'g196', 'fuv', 'aa', 't1d0', 'g12w', 'fm5']),
 ('idea', 'multiverse', 'Every universe at once', 'Todos los universos a la vez',
  "The multiverse: Rick's infinite Mortys, Miles among the Spider-People, three Peter Parkers on one bridge, and Evelyn with hot dog fingers.",
  'El multiverso: los infinitos Mortys de Rick, Miles entre los Spider-Man, tres Peter Parker en un mismo puente y Evelyn con dedos de salchicha.',
  ['t1d7', 'fmq', 'fj5', 'fj3', 'fil']),
 ('idea', 'space', 'Into space', 'Hacia el espacio',
  "Going up there: Apollo 13 coming home, two brothers who promised the moon, Cooper through the wormhole, Mark Watney's potatoes, a wooden ship in Outer Wilds, and Ryland Grace waking up alone.",
  'Subir allí arriba: el regreso del Apolo 13, dos hermanos que se prometieron la luna, Cooper atravesando el agujero de gusano, las patatas de Mark Watney, una nave de madera en Outer Wilds y Ryland Grace despertando solo.',
  ['fw6', 'm96', 'fod', 'fnz', 'g12w', 'bdy', 'fhv']),
 ('idea', 'contact', 'First contact', 'Primer contacto',
  "Meeting someone not from here: E.T. in the closet, the Trisolarans' signal, the heptapods' circles, and Rocky in Project Hail Mary.",
  'Conocer a alguien que no es de aquí: E.T. en el armario, la señal de los trisolarianos, los círculos de los heptápodos y Rocky en Proyecto Hail Mary.',
  ['fyo', 'bh8', 'fnk', 'bdy']),
 ('idea', 'outbreak', 'Outbreak', 'Brote',
  "Contagion: Rage-infected London, the last man in New York, a plague you design, the cordyceps, a county in Kentucky, and a world war against the dead.",
  'Contagio: un Londres infectado de Ira, el último hombre de Nueva York, una plaga que diseñas tú, el cordyceps, un condado de Kentucky y una guerra mundial contra los muertos.',
  ['fuc', 'frx', 'g162', 'g15o', 'g15g', 'fp1']),
 ('idea', 'afterend', 'After the end', 'Después del fin',
  "Life after the end of the world: Nausicaä's toxic jungle, a café on a quiet, sinking coast, the last pregnancy on Earth, Robert Neville's New York, the Mojave, Joel and Ellie's road, and the Citadel.",
  'La vida después del fin del mundo: la jungla tóxica de Nausicaä, una cafetería en una costa tranquila que se hunde, el último embarazo de la Tierra, la Nueva York de Robert Neville, el Mojave, el camino de Joel y Ellie y la Ciudadela.',
  ['a2g', 'm9b', 'fsl', 'frx', 'g166', 'g15o', 'fo6']),
 ('idea', 'dreams', 'Inside a dream', 'Dentro de un sueño',
  "Dreams on screen and in play: an old professor's nightmares, Guido's fantasies, Mulholland Drive, Psychonauts' minds, Inception's levels, and Headquarters in Riley's head.",
  'Sueños en pantalla y en juego: las pesadillas de un viejo profesor, las fantasías de Guido, Mulholland Drive, las mentes de Psychonauts, los niveles de Origen y el cuartel general en la cabeza de Riley.',
  ['fkq', 'fjz', 'fur', 'g18d', 'fqk', 'fo5']),
 ('idea', 'mindgames', 'Games of wits', 'Juegos de ingenio',
  "Battles fought with the mind: chess with Death, Light against L, Usogui's gambles, and Beth Harmon's board.",
  'Batallas de ingenio: ajedrez con la Muerte, Light contra L, las apuestas de Usogui y el tablero de Beth Harmon.',
  ['fku', 'a1', 'm99', 't1cr']),
 ('idea', 'press', 'The story at any cost', 'La noticia a cualquier precio',
  "The press and its temptations: a reporter keeping a man trapped in a cave, a columnist who ruins lives, a network anchor who is mad as hell, and Ankh-Morpork's first newspaper.",
  'La prensa y sus tentaciones: un periodista que mantiene a un hombre atrapado en una cueva, un columnista que arruina vidas, un presentador harto de todo y el primer periódico de Ankh-Morpork.',
  ['fle', 'fkr', 'fzk', 'bev']),
 ('idea', 'courtroom', 'Order in the court', 'Orden en la sala',
  "Trials: a surprise witness, twelve jurors, the judges at Nuremberg, Jake Brigance in Mississippi, the Guildford Four, a defence built on a lie, and Phoenix Wright's objections.",
  'Juicios: un testigo sorpresa, doce jurados, los jueces de Núremberg, Jake Brigance en Misisipi, los Cuatro de Guildford, una defensa construida sobre una mentira y las protestas de Phoenix Wright.',
  ['fkm', 'fkt', 'fk4', 'ban', 'fwo', 'fvv', 'g18c']),
 ('idea', 'prison', 'Behind bars', 'Entre rejas',
  "Prisons and escapes: a tunnel under La Santé, McMurphy in the ward, Andy Dufresne's poster, John Coffey on the Green Mile, and a prison you build yourself.",
  'Cárceles y fugas: un túnel bajo La Santé, McMurphy en el pabellón, el póster de Andy Dufresne, John Coffey en la Milla Verde y una cárcel que construyes tú mismo.',
  ['fkd', 'fzo', 'fwf', 'fv9', 'g14r']),
 ('idea', 'teachers', 'Teachers', 'Profesores',
  "Teachers who change everything: O Captain! My Captain!, a delinquent teacher, Sean Maguire's 'it's not your fault', and Fletcher, who pushes too far.",
  'Profesores que lo cambian todo: ¡Oh capitán, mi capitán!, un profesor delincuente, el "no es culpa tuya" de Sean Maguire y Fletcher, que va demasiado lejos.',
  ['fxk', 'm8w', 'fvp', 'fop']),
 ('idea', 'otherness', 'Seen at last', 'Por fin vistos',
  "People the world looks past: John Merrick, Raymond Babbitt, Forrest, Max writing to a girl across the world, and a deaf girl bullied at school.",
  'Personas que el mundo pasa por alto: John Merrick, Raymond Babbitt, Forrest, Max escribiendo a una niña al otro lado del mundo y una chica sorda acosada en el colegio.',
  ['fyy', 'fxm', 'fwh', 'frc', 'a29']),
 ('idea', 'food', 'Cooking', 'Cocinar',
  "Cooking as a calling: a rat in a Paris kitchen, monster stew in a dungeon, and Carmy's Chicago kitchen.",
  'La cocina como vocación: una rata en una cocina de París, guiso de monstruos en una mazmorra y la cocina de Carmy en Chicago.',
  ['fs8', 'm7q', 't1c9']),
 ('idea', 'dogs', 'Good dogs', 'Buenos perros',
  "Dogs: a spaghetti dinner, ninety-nine puppies, a TV dog who thinks his powers are real, Hachikō waiting at the station, Atari's search on Trash Island, and a dog's view of a haunted house.",
  'Perros: una cena de espaguetis, noventa y nueve cachorros, un perro de televisión que cree que sus poderes son reales, Hachikō esperando en la estación, la búsqueda de Atari en la Isla Basura y una casa encantada vista por un perro.',
  ['fkz', 'fk8', 'frg', 'fr5', 'fmy', 'fiz']),
 ('idea', 'deconstruct', 'Heroes, taken apart', 'Los héroes, desmontados',
  "Superheroes looked at hard: an old Batman, the Watchmen, Kingdom Come's last generation, Invincible's father, a hero bored by winning, an old Wolverine, and The Boys.",
  'Superhéroes mirados con dureza: un Batman viejo, los Watchmen, la última generación de Kingdom Come, el padre de Invencible, un héroe aburrido de ganar, un Lobezno viejo y The Boys.',
  ['chn', 'cb6', 'cgx', 'ccd', 'm8v', 'fnb', 't1cw']),
 ('idea', 'andes', 'The Andes, 1972', 'Los Andes, 1972',
  "The same true story told twice: the Uruguayan rugby team's plane down in the Andes, in Alive and in Society of the Snow.",
  'La misma historia real contada dos veces: el avión del equipo de rugby uruguayo caído en los Andes, en ¡Viven! y en La sociedad de la nieve.',
  ['fwv', 'fih']),
 # ---------------- myths and old stories ----------------
 ('source', 'greek', 'Greek myths, retold', 'Mitos griegos, contados de nuevo',
  "Greek myth across the map: Disney's Hercules, Kratos's war on Olympus, Achilles and Patroclus, Apotheon's black-figure pottery, Circe's island, Hades' escape from the underworld, and Nolan's Odyssey.",
  'La mitología griega por el mapa: el Hércules de Disney, la guerra de Kratos contra el Olimpo, Aquiles y Patroclo, la cerámica de figuras negras de Apotheon, la isla de Circe, la huida del inframundo de Hades y la Odisea de Nolan.',
  ['fvt', 'g18e', 'bfc', 'g152', 'baw', 'g12a', 'fhs']),
 ('source', 'norse', 'Norse myths and sagas', 'Mitos y sagas nórdicos',
  "The North: Vinland Saga's Icelanders, Marvel's Thor and his Ragnarok, Kratos and Atreus in Midgard, and The Northman's Amleth, the legend Hamlet came from.",
  'El Norte: los islandeses de Vinland Saga, el Thor de Marvel y su Ragnarok, Kratos y Atreus en Midgard, y el Amleth de El hombre del norte, la leyenda de la que salió Hamlet.',
  ['m5t', 'fq7', 'fn5', 'g13e', 'fj2', 'g11o']),
 ('source', 'arthur', 'King Arthur', 'El rey Arturo',
  "Arthurian legend: Disney's Wart pulling the sword, the Pythons' coconuts, Boorman's Excalibur, and The Seven Deadly Sins, whose world has its own Arthur and Merlin.",
  'La leyenda artúrica: el Wart de Disney sacando la espada, los cocos de los Monty Python, el Excalibur de Boorman y Los siete pecados capitales, cuyo mundo tiene su propio Arturo y su Merlín.',
  ['fjt', 'fzt', 'fyw', 'ay']),
 ('source', 'yokai', 'Spirits of old Japan', 'Espíritus del viejo Japón',
  "Japan's ghosts and gods: Mizoguchi's Ugetsu from Ueda Akinari's tales, Kobayashi's Kwaidan from Lafcadio Hearn's, the forest gods of Mononoke, and the bathhouse of the spirits.",
  'Fantasmas y dioses de Japón: el Ugetsu de Mizoguchi, sacado de los cuentos de Ueda Akinari, el Kwaidan de Kobayashi, sacado de los de Lafcadio Hearn, los dioses del bosque de La princesa Mononoke y la casa de baños de los espíritus.',
  ['fl8', 'fjm', 'a14', 'a12']),
 ('source', 'dante', "Dante's circles", 'Los círculos de Dante',
  "The Divine Comedy's long reach: Se7en's killer works through the deadly sins while Somerset reads Dante, and Devil May Cry's Dante and Vergil take their names from the poet and his guide.",
  'El largo alcance de la Divina comedia: el asesino de Seven recorre los pecados capitales mientras Somerset lee a Dante, y el Dante y el Vergil de Devil May Cry toman sus nombres del poeta y de su guía.',
  ['fw3', 'g185', 'g130']),
 # ---------------- directors, creators, studios ----------------
 ('maker', 'villeneuve', 'Denis Villeneuve', 'Denis Villeneuve',
  "Denis Villeneuve's films across the map: a family secret in Lebanon, a kidnapping in Pennsylvania, the heptapods, Los Angeles 2049 and Arrakis.",
  'Las películas de Denis Villeneuve por el mapa: un secreto familiar en el Líbano, un secuestro en Pensilvania, los heptápodos, Los Ángeles 2049 y Arrakis.',
  ['fqh', 'fox', 'fnk', 'fn4', 'fja', 'fic']),
 ('maker', 'spielberg', 'Steven Spielberg', 'Steven Spielberg',
  "Steven Spielberg's films on the map, from Jaws to The Fabelmans, his own story.",
  'Las películas de Steven Spielberg del mapa, de Tiburón a Los Fabelman, su propia historia.',
  ['fzr', 'fyu', 'fyo', 'fyf', 'fxl', 'fwu', 'fwp', 'fvi', 'frq', 'fmv', 'fiw']),
 ('maker', 'fincher', 'David Fincher', 'David Fincher',
  "David Fincher's dark precision: Se7en, Fight Club, The Social Network, and the FBI interviews of Mindhunter, which he produced and directed.",
  'La precisión oscura de David Fincher: Seven, El club de la lucha, La red social y los interrogatorios del FBI de Mindhunter, que produjo y dirigió.',
  ['fw3', 'fvb', 'fqg', 't1c6']),
 ('maker', 'eastwood', 'Clint Eastwood', 'Clint Eastwood',
  "Clint Eastwood in front of the camera for Leone, then behind it: the Man with No Name, High Plains Drifter, Josey Wales, Unforgiven, Iwo Jima from the Japanese side, Gran Torino and Sully.",
  'Clint Eastwood delante de la cámara para Leone y luego detrás: el Hombre sin Nombre, Infierno de cobardes, Josey Wales, Sin perdón, Iwo Jima desde el lado japonés, Gran Torino y Sully.',
  ['fjq', 'fjj', 'f10q', 'f105', 'fzl', 'fx3', 'fsg', 'frd', 'fnj']),
 ('maker', 'coppola', 'Francis Ford Coppola', 'Francis Ford Coppola',
  "Francis Ford Coppola: the Godfather saga, Apocalypse Now, and his Bram Stoker's Dracula.",
  'Francis Ford Coppola: la saga de El padrino, Apocalypse Now y su Drácula de Bram Stoker.',
  ['f109', 'fzv', 'fz7', 'fxc', 'fwz']),
 ('maker', 'zemeckis', 'Robert Zemeckis', 'Robert Zemeckis',
  "Robert Zemeckis: the Back to the Future trilogy, Forrest Gump and The Polar Express.",
  'Robert Zemeckis: la trilogía de Regreso al futuro, Forrest Gump y Polar Express.',
  ['fy5', 'fxi', 'fxh', 'fwh', 'fth']),
 ('maker', 'burton', 'Tim Burton', 'Tim Burton',
  "Tim Burton's gothic whimsy: Edward Scissorhands, The Nightmare Before Christmas (his story, which he produced), Willy Wonka's factory, his Alice, and Wednesday.",
  'La fantasía gótica de Tim Burton: Eduardo Manostijeras, Pesadilla antes de Navidad (su historia, que produjo), la fábrica de Willy Wonka, su Alicia y Miércoles.',
  ['fxd', 'fwq', 'ft6', 'fqu', 't1cl']),
 ('maker', 'raimi', 'Sam Raimi', 'Sam Raimi',
  "Sam Raimi from the cabin in the woods to New York: the Evil Dead films and his Spider-Man trilogy.",
  'Sam Raimi, de la cabaña en el bosque a Nueva York: las películas de Evil Dead y su trilogía de Spider-Man.',
  ['fys', 'fxw', 'fx1', 'fuk', 'ftk', 'fse']),
 ('maker', 'boyle', 'Danny Boyle', 'Danny Boyle',
  "Danny Boyle: Trainspotting, the Rage virus of 28 Days Later, and Renton's return twenty years on.",
  'Danny Boyle: Trainspotting, el virus de la Ira de 28 días después y el regreso de Renton veinte años después.',
  ['fvx', 'fuc', 'fne']),
 ('maker', 'eggers', 'Robert Eggers', 'Robert Eggers',
  "Robert Eggers's history as horror: a Puritan family, two lighthouse keepers, and a Viking prince.",
  'La historia como terror de Robert Eggers: una familia puritana, dos fareros y un príncipe vikingo.',
  ['fo9', 'fmo', 'fj2']),
 ('maker', 'wesanderson', 'Wes Anderson', 'Wes Anderson',
  "Wes Anderson's symmetrical worlds: Mr. Fox, the Grand Budapest Hotel and Trash Island.",
  'Los mundos simétricos de Wes Anderson: el señor Fox, el Gran Hotel Budapest y la Isla Basura.',
  ['fqx', 'foo', 'fmy']),
 ('maker', 'moore', 'Alan Moore', 'Alan Moore',
  "Alan Moore's comics: Watchmen, The Killing Joke and V for Vendetta, and Snyder's Watchmen.",
  'Los cómics de Alan Moore: Watchmen, La broma asesina y V de Vendetta, y el Watchmen de Snyder.',
  ['cb6', 'cf7', 'chh', 'fra']),
 ('maker', 'miller', 'Frank Miller', 'Frank Miller',
  "Frank Miller's hard-boiled comics: The Dark Knight Returns, Batman: Year One and Sin City, and the animated films made from them.",
  'Los cómics duros de Frank Miller: El regreso del Caballero Oscuro, Batman: Año uno y Sin City, y las películas animadas basadas en ellos.',
  ['chn', 'cgh', 'bg9', 'fpv', 'fpd']),
 ('maker', 'loeb', 'Jeph Loeb', 'Jeph Loeb',
  "Jeph Loeb's comics, most of them drawn by Tim Sale: the Long Halloween books, Spider-Man: Blue, and Hush with Jim Lee.",
  'Los cómics de Jeph Loeb, casi todos dibujados por Tim Sale: los libros de El largo Halloween, Spider-Man: Azul y Silencio con Jim Lee.',
  ['ccp', 'cd2', 'cch', 'cc7', 'cb5']),
 ('maker', 'brucelee', 'Bruce Lee', 'Bruce Lee',
  "Bruce Lee's films, and Kill Bill, whose yellow tracksuit is his from Game of Death.",
  'Las películas de Bruce Lee, y Kill Bill, cuyo chándal amarillo es el suyo de Juego con la muerte.',
  ['f108', 'f106', 'f103', 'fu1']),
 ('maker', 'oshii', 'Mamoru Oshii', 'Mamoru Oshii',
  "Mamoru Oshii: the wordless Angel's Egg and Ghost in the Shell.",
  'Mamoru Oshii: el silencioso Angel\'s Egg y Ghost in the Shell.',
  ['a2a', 'a1s']),
 ('maker', 'imaishi', 'Hiroyuki Imaishi', 'Hiroyuki Imaishi',
  "Hiroyuki Imaishi directed Gurren Lagann, then Cyberpunk: Edgerunners at Studio Trigger.",
  'Hiroyuki Imaishi dirigió Gurren Lagann y después Cyberpunk: Edgerunners en Studio Trigger.',
  ['a45', 'a2d']),
 ('maker', 'inoue', 'Takehiko Inoue', 'Takehiko Inoue',
  "Takehiko Inoue's basketball and swords: Slam Dunk, Vagabond, Real, and The First Slam Dunk, which he wrote and directed.",
  'El baloncesto y las espadas de Takehiko Inoue: Slam Dunk, Vagabond, Real y The First Slam Dunk, que escribió y dirigió.',
  ['m66', 'm5v', 'm8u', 'a2f']),
 ('maker', 'miyamoto', 'Shigeru Miyamoto', 'Shigeru Miyamoto',
  "Games Shigeru Miyamoto created, directed or produced: Super Mario Bros., Super Mario World, Super Mario 64, Ocarina of Time and Pikmin.",
  'Juegos que Shigeru Miyamoto creó, dirigió o produjo: Super Mario Bros., Super Mario World, Super Mario 64, Ocarina of Time y Pikmin.',
  ['g1ae', 'g1a6', 'g19n', 'g19c', 'g127']),
 ('maker', 'valve', 'Valve', 'Valve',
  "Valve's games across the map: Half-Life, Counter-Strike, Portal and Left 4 Dead.",
  'Los juegos de Valve por el mapa: Half-Life, Counter-Strike, Portal y Left 4 Dead.',
  ['g19d', 'g193', 'g18i', 'g17q', 'g17a', 'g16l', 'g160', 'g12m']),
 ('maker', 'konami', "Konami's golden age", 'La edad de oro de Konami',
  "Konami from the NES to the PS2: Castlevania, Contra, Symphony of the Night, Metal Gear Solid and Silent Hill.",
  'Konami de la NES a la PS2: Castlevania, Contra, Symphony of the Night, Metal Gear Solid y Silent Hill.',
  ['g1ac', 'g1ab', 'g1a3', 'g19l', 'g19e', 'g19a', 'g190', 'g191', 'g18h']),
 ('maker', 'telltale', 'Telltale Games', 'Telltale Games',
  "Telltale's choose-and-live-with-it stories: The Walking Dead, The Wolf Among Us, Tales from the Borderlands and Batman.",
  'Las historias de Telltale en las que eliges y cargas con ello: The Walking Dead, The Wolf Among Us, Tales from the Borderlands y Batman.',
  ['g164', 'g15k', 'g15f', 'g153', 'g144']),
 ('maker', 'respawn', 'Respawn Entertainment', 'Respawn Entertainment',
  "Respawn's games: Titanfall 2, Apex Legends and Jedi: Fallen Order.",
  'Los juegos de Respawn: Titanfall 2, Apex Legends y Jedi: Fallen Order.',
  ['g140', 'g133', 'g12p']),
 ('maker', 'suckerpunch', 'Sucker Punch', 'Sucker Punch',
  "Sucker Punch's games: Infamous 2's superpowered New Marais and Ghost of Tsushima.",
  'Los juegos de Sucker Punch: la New Marais con superpoderes de Infamous 2 y Ghost of Tsushima.',
  ['g16j', 'g12f']),
 ('maker', 'rare', 'Rare', 'Rare',
  "Rare's 90s platformers: Donkey Kong Country and Banjo-Kazooie.",
  'Los plataformas noventeros de Rare: Donkey Kong Country y Banjo-Kazooie.',
  ['g19t', 'g19f']),
 # ---------------- composers ----------------
 ('score', 'herrmann', "Bernard Herrmann's scores", 'Las bandas sonoras de Bernard Herrmann',
  "Bernard Herrmann from Citizen Kane to Taxi Driver, his last score, by way of Hitchcock's Vertigo, North by Northwest and Psycho's shower strings.",
  'Bernard Herrmann de Ciudadano Kane a Taxi Driver, su última banda sonora, pasando por Vértigo, Con la muerte en los talones y los violines de la ducha de Psicosis de Hitchcock.',
  ['fls', 'fkl', 'fkh', 'fkb', 'fzm']),
 ('score', 'rota', "Nino Rota's scores", 'Las bandas sonoras de Nino Rota',
  "Nino Rota for Fellini and Visconti, then the Godfather's waltz.",
  'Nino Rota para Fellini y Visconti, y después el vals de El padrino.',
  ['fks', 'fke', 'fka', 'fjz', 'f109', 'm1en', 'fzv']),
 ('score', 'silvestri', "Alan Silvestri's scores", 'Las bandas sonoras de Alan Silvestri',
  "Alan Silvestri: Back to the Future, Predator, Forrest Gump, The Polar Express and the Avengers.",
  'Alan Silvestri: Regreso al futuro, Depredador, Forrest Gump, Polar Express y los Vengadores.',
  ['fy5', 'fxt', 'fxi', 'fxh', 'fwh', 'fth', 'fpz', 'fpo', 'fmv', 'fmu', 'fmp']),
 ('score', 'horner', "James Horner's scores", 'Las bandas sonoras de James Horner',
  "James Horner: Aliens, Braveheart, Apollo 13, Titanic (his Oscars), Avatar and The Amazing Spider-Man.",
  'James Horner: Aliens, Braveheart, Apolo 13, Titanic (sus Óscar), Avatar y The Amazing Spider-Man.',
  ['fy0', 'fw9', 'fw6', 'fvr', 'fqw', 'fpk']),
 ('score', 'shore', "Howard Shore's scores", 'Las bandas sonoras de Howard Shore',
  "Howard Shore: The Silence of the Lambs, Se7en, Middle-earth (three Oscars for The Lord of the Rings) and The Departed.",
  'Howard Shore: El silencio de los corderos, Seven, la Tierra Media (tres Óscar por El Señor de los Anillos) y Infiltrados.',
  ['fxb', 'fw3', 'ful', 'fua', 'm1eq', 'ftx', 'fsk', 'fpg']),
 ('score', 'elfman', "Danny Elfman's scores", 'Las bandas sonoras de Danny Elfman',
  "Danny Elfman: The Simpsons' theme, Tim Burton's films, Raimi's Spider-Man and Wednesday.",
  'Danny Elfman: la sintonía de Los Simpson, las películas de Tim Burton, el Spider-Man de Raimi y Miércoles.',
  ['t1bx', 'fxd', 'fwq', 'fuk', 'ftk', 'ft6', 'fqu', 't1cl']),
 ('score', 'giacchino', "Michael Giacchino's scores", 'Las bandas sonoras de Michael Giacchino',
  "Michael Giacchino for Pixar (Up won him the Oscar), Star Trek, Rogue One, the MCU's Spider-Man and The Batman.",
  'Michael Giacchino para Pixar (Up le dio el Óscar), Star Trek, Rogue One, el Spider-Man del UCM y The Batman.',
  ['ftg', 'fs8', 'fr8', 'fr7', 'fp7', 'fo5', 'fnf', 'fn9', 'fn3', 'fj5', 'fj4']),
 ('score', 'djawadi', "Ramin Djawadi's scores", 'Las bandas sonoras de Ramin Djawadi',
  "Ramin Djawadi: Iron Man, Westeros's main title and the Fallout series.",
  'Ramin Djawadi: Iron Man, la cabecera de Poniente y la serie de Fallout.',
  ['frt', 't1dq', 't1cg', 't1bz']),
 ('score', 'goransson', "Ludwig Göransson's scores", 'Las bandas sonoras de Ludwig Göransson',
  "Ludwig Göransson: Black Panther and Oppenheimer (both Oscars), The Mandalorian, Tenet and Sinners.",
  'Ludwig Göransson: Black Panther y Oppenheimer (los dos con Óscar), The Mandalorian, Tenet y Los pecadores.',
  ['fmz', 't1cu', 'fm5', 'fii', 'm1jm', 'fi3']),
 ('score', 'reznor', 'Trent Reznor and Atticus Ross', 'Trent Reznor y Atticus Ross',
  "Nine Inch Nails' Trent Reznor, then with Atticus Ross on film: The Social Network and Soul both won them the Oscar.",
  'Trent Reznor de Nine Inch Nails, y después con Atticus Ross en el cine: La red social y Soul les dieron el Óscar.',
  ['m1ld', 'm1le', 'fqg', 'fm4']),
 ('score', 'hildur', 'Hildur Guðnadóttir', 'Hildur Guðnadóttir',
  "Hildur Guðnadóttir's cellos: Chernobyl (an Emmy) and Joker (the Oscar), months apart.",
  'Los violonchelos de Hildur Guðnadóttir: Chernobyl (un Emmy) y Joker (el Óscar), con meses de diferencia.',
  ['t1cs', 'fmf']),
 ('score', 'daftpunk', 'Daft Punk', 'Daft Punk',
  "Daft Punk's Discovery, the anime film made of it with Leiji Matsumoto, and their score for TRON: Legacy.",
  'Discovery de Daft Punk, la película de anime que se hizo con él junto a Leiji Matsumoto y su banda sonora para TRON: Legacy.',
  ['m1id', 'fu6', 'fqd']),
 ('score', 'floyd', 'Pink Floyd', 'Pink Floyd',
  "Pink Floyd's albums and Alan Parker's film of The Wall.",
  'Los discos de Pink Floyd y la película de Alan Parker sobre The Wall.',
  ['m1m1', 'm1m2', 'm1m3', 'm1m4', 'm1m5', 'fyp', 'm1m6']),
]

# How each connection in ROUTES is grouped in the ledger.
KIND = {'idea': {'nietzsche', 'existence', 'faith', 'mortality', 'mind', 'real', 'fate', 'state', 'ideologies', 'hatred', 'fall', 'bushido', 'balance', 'nature', 'pessimism', 'freedom', 'family', 'inherited', 'revenge', 'american', 'memory', 'greatness'},
        'maker': {'toriyama', 'martin', 'naughtydog', 'kamiya', 'insomniac', 'coens', 'ridley', 'watanabe', 'urobuchi'},
        'score': {'morricone', 'zimmer', 'williams'},
        'canon': {'big3seinen', 'big3shonen', 'cosmere', 'shooters', 'square', 'hbo'}}
kind_of = lambda rid: next((k for k, ids in KIND.items() if rid in ids), 'influence')
out, bad = [], []
for kind, rid, name, name_es, blurb, blurb_es, stops in [(kind_of(r[0]),) + r for r in ROUTES] + MORE:
    miss = [s for s in stops if s not in items]
    if miss: bad.append((rid, miss)); stops = [s for s in stops if s in items]
    if len(stops) < 2: continue
    out.append({'id': rid, 'kind': kind, 'name': name, 'name_es': name_es, 'blurb': blurb, 'blurb_es': blurb_es, 'items': stops})
W['routes'] = out
print(f'{len(out)} connections' + (f', missing works: {bad}' if bad else ''))
(SITE / 'index.html').write_text(html[:m.start(2)] + json.dumps(W, ensure_ascii=False, separators=(',', ':')) + html[m.end(2):])
